// 계정 삭제
DROP USER c##test CASCADE;
// 계정 생성
CREATE USER c##test IDENTIFIED BY test DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp PROFILE DEFAULT;
GRANT CONNECT, RESOURCE TO c##test;
GRANT CREATE VIEW, CREATE SYNONYM TO c##test;
GRANT UNLIMITED TABLESPACE TO c##test;
ALTER USER c##test ACCOUNT UNLOCK;